name: tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  linux_tests:
    strategy:
      fail-fast: true
      matrix:
        os: [
          # windows-2022,
          # windows-2019,
          ubuntu-22.04,
          macos-12,
          macos-11
        ]
        php: [
          # 5.3,
          # 5.4,
          # 5.5,
          # 5.6,
          # '7.0',
          # 7.1,
          # 7.2,
          7.3,
          7.4,
          '8.0',
          8.1,
          8.2
        ]
        stability: [prefer-lowest, prefer-stable]

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Execute tests
        run: php dove.php

      - name: Benchmarking
        run: php benchmark.php